# Generated by Django 2.0.2 on 2018-03-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='updated_at',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='created_at',
            new_name='start_date',
        ),
    ]
