# Generated by Django 2.0.2 on 2018-03-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180327_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='work_day_started',
            field=models.BooleanField(default=False),
        ),
    ]
