# Generated by Django 2.0.2 on 2018-03-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_activity_work_day_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='work_day_started',
        ),
        migrations.AddField(
            model_name='module',
            name='work_day_started',
            field=models.BooleanField(default=False),
        ),
    ]
